### ISSUE TITLE
LXC 3.2.1 and LXCFS 3.1.2 Released

### ISSUE THREAD

**Issue by lemonzest79** [ganto/copr-lxc3#16]
LXC 3.2.1 and LXCFS 3.1.2 Released on the 24th of July 2019 are there any plans on building these for fedora 30?

**Comment by ganto** [comment]
Sorry, I missed that completely. Sure, I'll do that in the next few days.

**Comment by ganto** [comment]
Packages are ready to use. Please let me know if you find some issues.

**Comment by lemonzest79** [comment]
Thanks, just installed LXC 3.2.1 and everything still worked correctly for my unprivileged container test
