### ISSUE TITLE
4.0 LTS versions of LXC/LXD/LXCFS available

### ISSUE THREAD

**Issue by lemonzest79** [ganto/copr-lxc3#23]
Hello, just a quick message to ask if these are planned on being built? many thanks for your time and efforts :)

**Comment by ganto** [comment]
Ya, I slowly started with it at [ganto/lxc4](https://copr.fedorainfracloud.org/coprs/ganto/lxc4). There I'll track the latest upstream releases but currently only for Fedora.

Please be careful, I'd first like to build all the packages and run some tests before people should use it. During this time, I might completely wipe the repo if necessary.

**Comment by ganto** [comment]
LXC/LXD versions from the lxc4 COPR repository are ready to be used. This lxc3 repository won't be updated anymore.
