### ISSUE TITLE
LXD 3.22 on Fedora 32

### ISSUE THREAD

**Issue by edgan** [ganto/copr-lxc3#24]
I know you are working on LXD 4 for Fedora, but I got into a pickle. I had lxd 3.22 from Fedora 31, and upgraded to Fedora 32. This worked just fine till I uninstalled lxd 3.22 and tried to reinstall it. I found I only got 3.21 for Fedora 32. But then lxd wouldn't start because the "data" version was higher. I tried to compile 3.22 for Fedora 32, but that failed on tests. I then set the $releasever in the repo file to 31 and reinstalled 3.22. It would be nice if people could just straight install 3.22 on Fedora 32 until 4 is avaliable.

**Comment by ganto** [comment]
It seems that at the moment the only way you can make the spec file successfully build on Fedora 32 is to disable the failing test.

**Comment by nickvanderstel** [comment]
I think an issue I'm having might be related to this. More details can be found [here](https://discuss.linuxcontainers.org/t/lxd-containers-service-fails-to-start-after-upgrade-to-fedora-32/9046) but it seems like after upgrading from Fedora 31 to 32, my LXD was downgraded. I'm showing version 3.20 of both LXD and LXC and that's the most recent listed in both ganto-lxc3 and the base fedora repos. Any advice? Is version 4 fairly stable?

**Comment by ganto** [comment]
Ah, sorry. Yes, I use the ganto/copr-lxc4 repository for a while now and was finally able to fix the Fedora 32 package a few weeks ago. It should work fine. I didn't take my time to update the documentation yet but give it a try.

**Comment by nickvanderstel** [comment]
I upgraded to lxc4 and everything seems to be in working order again. Thanks!
